/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AuthedRouteImport } from './routes/_authed'
import { Route as AuthedIndexRouteImport } from './routes/_authed/index'
import { Route as AuthedSettingsRouteImport } from './routes/_authed/settings'
import { Route as AuthedScheduleRouteImport } from './routes/_authed/schedule'
import { Route as AuthedRolesRouteImport } from './routes/_authed/roles'
import { Route as AuthedMyRouteImport } from './routes/_authed/my'
import { Route as AuthedMembersRouteImport } from './routes/_authed/members'
import { Route as AuthedClassesRouteImport } from './routes/_authed/classes'
import { Route as AuthedActivityRouteImport } from './routes/_authed/activity'

const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthedRoute = AuthedRouteImport.update({
  id: '/_authed',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthedIndexRoute = AuthedIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedSettingsRoute = AuthedSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedScheduleRoute = AuthedScheduleRouteImport.update({
  id: '/schedule',
  path: '/schedule',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedRolesRoute = AuthedRolesRouteImport.update({
  id: '/roles',
  path: '/roles',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedMyRoute = AuthedMyRouteImport.update({
  id: '/my',
  path: '/my',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedMembersRoute = AuthedMembersRouteImport.update({
  id: '/members',
  path: '/members',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedClassesRoute = AuthedClassesRouteImport.update({
  id: '/classes',
  path: '/classes',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedActivityRoute = AuthedActivityRouteImport.update({
  id: '/activity',
  path: '/activity',
  getParentRoute: () => AuthedRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof AuthedIndexRoute
  '/login': typeof LoginRoute
  '/activity': typeof AuthedActivityRoute
  '/classes': typeof AuthedClassesRoute
  '/members': typeof AuthedMembersRoute
  '/my': typeof AuthedMyRoute
  '/roles': typeof AuthedRolesRoute
  '/schedule': typeof AuthedScheduleRoute
  '/settings': typeof AuthedSettingsRoute
}
export interface FileRoutesByTo {
  '/login': typeof LoginRoute
  '/activity': typeof AuthedActivityRoute
  '/classes': typeof AuthedClassesRoute
  '/members': typeof AuthedMembersRoute
  '/my': typeof AuthedMyRoute
  '/roles': typeof AuthedRolesRoute
  '/schedule': typeof AuthedScheduleRoute
  '/settings': typeof AuthedSettingsRoute
  '/': typeof AuthedIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_authed': typeof AuthedRouteWithChildren
  '/login': typeof LoginRoute
  '/_authed/activity': typeof AuthedActivityRoute
  '/_authed/classes': typeof AuthedClassesRoute
  '/_authed/members': typeof AuthedMembersRoute
  '/_authed/my': typeof AuthedMyRoute
  '/_authed/roles': typeof AuthedRolesRoute
  '/_authed/schedule': typeof AuthedScheduleRoute
  '/_authed/settings': typeof AuthedSettingsRoute
  '/_authed/': typeof AuthedIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/activity'
    | '/classes'
    | '/members'
    | '/my'
    | '/roles'
    | '/schedule'
    | '/settings'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/login'
    | '/activity'
    | '/classes'
    | '/members'
    | '/my'
    | '/roles'
    | '/schedule'
    | '/settings'
    | '/'
  id:
    | '__root__'
    | '/_authed'
    | '/login'
    | '/_authed/activity'
    | '/_authed/classes'
    | '/_authed/members'
    | '/_authed/my'
    | '/_authed/roles'
    | '/_authed/schedule'
    | '/_authed/settings'
    | '/_authed/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AuthedRoute: typeof AuthedRouteWithChildren
  LoginRoute: typeof LoginRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authed': {
      id: '/_authed'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authed/': {
      id: '/_authed/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AuthedIndexRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/settings': {
      id: '/_authed/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof AuthedSettingsRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/schedule': {
      id: '/_authed/schedule'
      path: '/schedule'
      fullPath: '/schedule'
      preLoaderRoute: typeof AuthedScheduleRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/roles': {
      id: '/_authed/roles'
      path: '/roles'
      fullPath: '/roles'
      preLoaderRoute: typeof AuthedRolesRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/my': {
      id: '/_authed/my'
      path: '/my'
      fullPath: '/my'
      preLoaderRoute: typeof AuthedMyRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/members': {
      id: '/_authed/members'
      path: '/members'
      fullPath: '/members'
      preLoaderRoute: typeof AuthedMembersRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/classes': {
      id: '/_authed/classes'
      path: '/classes'
      fullPath: '/classes'
      preLoaderRoute: typeof AuthedClassesRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/activity': {
      id: '/_authed/activity'
      path: '/activity'
      fullPath: '/activity'
      preLoaderRoute: typeof AuthedActivityRouteImport
      parentRoute: typeof AuthedRoute
    }
  }
}

interface AuthedRouteChildren {
  AuthedActivityRoute: typeof AuthedActivityRoute
  AuthedClassesRoute: typeof AuthedClassesRoute
  AuthedMembersRoute: typeof AuthedMembersRoute
  AuthedMyRoute: typeof AuthedMyRoute
  AuthedRolesRoute: typeof AuthedRolesRoute
  AuthedScheduleRoute: typeof AuthedScheduleRoute
  AuthedSettingsRoute: typeof AuthedSettingsRoute
  AuthedIndexRoute: typeof AuthedIndexRoute
}

const AuthedRouteChildren: AuthedRouteChildren = {
  AuthedActivityRoute: AuthedActivityRoute,
  AuthedClassesRoute: AuthedClassesRoute,
  AuthedMembersRoute: AuthedMembersRoute,
  AuthedMyRoute: AuthedMyRoute,
  AuthedRolesRoute: AuthedRolesRoute,
  AuthedScheduleRoute: AuthedScheduleRoute,
  AuthedSettingsRoute: AuthedSettingsRoute,
  AuthedIndexRoute: AuthedIndexRoute,
}

const AuthedRouteWithChildren =
  AuthedRoute._addFileChildren(AuthedRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  AuthedRoute: AuthedRouteWithChildren,
  LoginRoute: LoginRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
